<?php

declare(strict_types=1);

namespace App\DTOs;

use Carbon\Carbon;

final class OsgorApplicationData
{
    // Default constants for OSGOR insurance
    private const DEFAULT_INSURANCE_RATE = 0.05710; // 5.71%
    private const DEFAULT_INSURANCE_TERM_ID = 4;
    private const DEFAULT_FUNERAL_EXPENSES_SUM = '1020000';
    private const DEFAULT_AREA_TYPE_ID = '1';
    private const DEFAULT_AGENCY_ID = '546';
    private const DEFAULT_OWNERSHIP_FORM_ID = '130';
    private const DEFAULT_COMMISSION = '0';
    private const DEFAULT_INSURANCE_AMOUNT = 50000000;

    public function __construct(
        public array $insurant,
        public array $policies,
        public string $number,
        public string $sum,
        public string $contractStartDate,
        public string $contractEndDate,
        public string $regionId,
        public string $areaTypeId,
        public string $agencyId,
        public string $comission,
        public float $insurancePremium,
    ) {}

    public static function fromRequest(array $data): self
    {
        // Extract dates from form (payment_start_date -> contract_start_date)
        $contractStartDate = $data['payment_start_date'] ?? Carbon::today()->format('Y-m-d');
        $contractEndDate = $data['payment_end_date'] ?? Carbon::today()->addYear()->format('Y-m-d');

        // Use same dates for policy start/end
        $startDate = $contractStartDate;
        $endDate = $contractEndDate;

        // Extract organization data from form
        $organization = $data['organization'] ?? [];

        // Get company info from session if available (from INN search)
        $companyInfo = session('osgor_company_info') ?? [];
        $companyData = $companyInfo['result'] ?? $companyInfo;

        // OKED: API expects code only (e.g. "86230"); form may send "86230 Title"
        $okedRaw = $organization['oked'] ?? '';
        $oked = trim(explode(' ', $okedRaw)[0] ?? $okedRaw) ?: $okedRaw;

        // Build insurant organization data per osgor_ozgop.MD (344-355)
        $insurant = [
            'organization' => [
                'inn' => $organization['inn'] ?? '',
                'name' => $organization['name'] ?? '',
                'representativeName' => $organization['representative_name']
                    ?? $companyData['representativeName']
                    ?? $companyData['representative_name']
                    ?? $organization['name']
                    ?? '',
                'address' => $organization['address'] ?? '',
                'oked' => $oked,
                'position' => $organization['position']
                    ?? $companyData['position']
                    ?? '',
                'checkingAccount' => $organization['checking_account']
                    ?? $companyData['checkingAccount']
                    ?? $companyData['checking_account']
                    ?? '',
                'phone' => $organization['phone'] ?? '',
                'regionId' => $organization['region_id'] ?? '',
                // Note: districtId is not in API format, only regionId is used
                'ownershipFormId' => $organization['ownership_form_id'] ?? self::DEFAULT_OWNERSHIP_FORM_ID,
            ],
        ];

        // Extract insurance amount from form
        $insuranceSum = (float) ($data['insurance_amount'] ?? self::DEFAULT_INSURANCE_AMOUNT);

        // Calculate insurance premium using default rate
        $insuranceRate = self::DEFAULT_INSURANCE_RATE;
        $insurancePremium = round($insuranceSum * $insuranceRate, 2);

        // Build policies per osgor_ozgop.MD (357-368)
        $policies = [
            [
                'issueDate' => $startDate,
                'startDate' => $startDate,
                'endDate' => $endDate,
                'insuranceSum' => number_format($insuranceSum, 2, '.', ''), // "443261886.34"
                'insuranceRate' => (string) self::DEFAULT_INSURANCE_RATE,   // "0.05710"
                'insurancePremium' => number_format($insurancePremium, 2, '.', ''), // "253102.54"
                'insuranceTermId' => self::DEFAULT_INSURANCE_TERM_ID,       // 4
                'funeralExpensesSum' => self::DEFAULT_FUNERAL_EXPENSES_SUM, // "1020000"
                'fot' => (float) $insuranceSum,                             // 443261886.34 (float)
            ],
        ];

        return new self(
            insurant: $insurant,
            policies: $policies,
            number: '', // Will be generated by API
            sum: number_format($insuranceSum, 2, '.', ''), // API: "443261886.34"
            contractStartDate: $contractStartDate,
            contractEndDate: $contractEndDate,
            regionId: $organization['region_id'] ?? '',
            areaTypeId: self::DEFAULT_AREA_TYPE_ID,
            agencyId: self::DEFAULT_AGENCY_ID,
            comission: self::DEFAULT_COMMISSION,
            insurancePremium: $insurancePremium,
        );
    }

    public function toArray(): array
    {
        return [
            'insurant' => $this->insurant,
            'policies' => $this->policies,
            'number' => $this->number,
            'sum' => $this->sum,
            'contractStartDate' => $this->contractStartDate,
            'contractEndDate' => $this->contractEndDate,
            'regionId' => $this->regionId,
            'areaTypeId' => $this->areaTypeId,
            'agencyId' => $this->agencyId,
            'comission' => $this->comission,
            'insurancePremium' => $this->insurancePremium,
        ];
    }

    public function toApiFormat(): array
    {
        return [
            'number' => $this->number,
            'sum' => $this->sum,
            'contractStartDate' => $this->contractStartDate,
            'contractEndDate' => $this->contractEndDate,
            'regionId' => $this->regionId,
            'areaTypeId' => $this->areaTypeId,
            'agencyId' => $this->agencyId,
            'comission' => $this->comission,
            'insurant' => $this->insurant,
            'policies' => $this->policies,
        ];
    }
}
